{{- if and .Values.adminToken.value (not .Values.adminToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mock-idp.fullname" . }}-admin-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-idp.labels" . | nindent 4 }}
stringData:
  admin-token: {{ .Values.adminToken.value | quote }}
{{- end }}
